table DimDate
	lineageTag: cccccccc-0000-0000-0000-000000000001

	column Date
		lineageTag: aaaaaaaa-0000-0000-0000-000000000001
		dataType: dateTime
		summarizeBy: none
		sourceColumn: Date
		formatString: Short Date

	column Month
		lineageTag: aaaaaaaa-0000-0000-0000-000000000002
		dataType: string
		summarizeBy: none
		sourceColumn: Month

	column Quarter
		lineageTag: aaaaaaaa-0000-0000-0000-000000000003
		dataType: string
		summarizeBy: none
		sourceColumn: Quarter

	column Year
		lineageTag: aaaaaaaa-0000-0000-0000-000000000004
		dataType: int64
		summarizeBy: none
		sourceColumn: Year

	partition DimDate = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WAgAA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Date = _t, Month = _t, Quarter = _t, Year = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Date", type datetime}, {"Month", type text}, {"Quarter", type text}, {"Year", Int64.Type}})
				in
				    #"Changed Type"
