table FactSales
	lineageTag: cccccccc-0000-0000-0000-000000000004

	column sale_id
		lineageTag: aaaaaaaa-0000-0000-0000-000000000030
		dataType: int64
		summarizeBy: none
		sourceColumn: sale_id

	column date_key
		lineageTag: aaaaaaaa-0000-0000-0000-000000000031
		dataType: dateTime
		summarizeBy: none
		sourceColumn: date_key
		formatString: Short Date

	column store_key
		lineageTag: aaaaaaaa-0000-0000-0000-000000000032
		dataType: int64
		summarizeBy: none
		sourceColumn: store_key

	column product_key
		lineageTag: aaaaaaaa-0000-0000-0000-000000000033
		dataType: int64
		summarizeBy: none
		sourceColumn: product_key

	column quantity
		lineageTag: aaaaaaaa-0000-0000-0000-000000000034
		dataType: int64
		summarizeBy: sum
		sourceColumn: quantity

	column revenue
		lineageTag: aaaaaaaa-0000-0000-0000-000000000035
		dataType: decimal
		summarizeBy: sum
		sourceColumn: revenue
		formatString: $#,##0.00

	partition FactSales = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WAgAA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [sale_id = _t, date_key = _t, store_key = _t, product_key = _t, quantity = _t, revenue = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"sale_id", Int64.Type}, {"date_key", type datetime}, {"store_key", Int64.Type}, {"product_key", Int64.Type}, {"quantity", Int64.Type}, {"revenue", type number}})
				in
				    #"Changed Type"
